# Generated by Django 5.2.4 on 2025-07-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gateway',
            name='io',
            field=models.CharField(blank=True, choices=[('input', 'Input'), ('output', 'Output')], max_length=10, null=True),
        ),
    ]
